name: C/C++ CI Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: Compile
      run: |
        cd Xmake
        cl Xmake.cpp function.cpp help.cpp Global.cpp 
